MyShop/MyShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter
from shop.api.urls import router as shop_router
from orders.api.urls import router as order_router
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView


router = DefaultRouter()
router.registry.extend(shop_router.registry)
router.registry.extend(order_router.registry)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include(router.urls)),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

MyShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

MyShop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.create_order, name='create_order'),
]

MyShop/shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

MyShop/cart/forms.py
from django import forms

QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int, label='Количество')
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

MyShop/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .cart import Cart
from shop.models import Product
from .forms import CartAddProductForm

# Create your views here.


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                          'override': True})

    return render(request, 'cart/cart_detail.html', {'cart': cart})


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

MyShop/cart/templates/cart/cart_detail.html
<!DOCTYPE html>
<html lang="ru">
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    <title>Корзина покупок</title>
{% endblock %}
{% block content %}
    <h1>Корзина</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Фото товара</th>
                <th>Товар</th>
                <th>Количество</th>
                <th>Удалить из корзины</th>
                <th>Цена за штуку</th>
                <th>Цена</th>
            </tr>
        </thead>
        <tbody>
            {% for cart_item in cart %}
                {% with product=cart_item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}{% endif %}">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ cart_item.update_quantity_form.quantity }}
                                {{ cart_item.update_quantity_form.override }}
                                <input type="submit" value="Обновить">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                <input type="submit" value="Remove">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td class="num">{{ cart_item.price }} ₽</td>
                        <td class="num">{{ cart_item.total_price }} ₽</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">{{ cart.get_total_price }} ₽</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">Продолжить покупки</a>
        <a href="{% url "orders:create_order" %}" class="button">Оформить заказ</a>
    </p>
{% endblock %}